### ISSUE TITLE
upgrade-ipam initContainer fails when calico-node is restarted

### ISSUE THREAD

**Issue by maxbischoff** [projectcalico/cni-plugin#749]
When upgrading from v3.5.4 to v3.7.2 we sometimes observed an issue where calico-node on single nodes sometimes fails to restart when its pod was killed due to upgrade-ipam failing, as migrate.go attempts to write IP addresses into ` IPAMBlock` which already contain those addresses. A symptom of this is upgrade-ipam not skipping migration, because `/var/lib/cni/networks/k8s-pod-network` is not properly cleaned.

## Expected Behavior

upgrade-ipam should skip migration in subsequent restarts of calico-node pods and therefore not fail.

## Current Behavior

Migration fails in `ipam.go` when assignin IPs in IPAMBlocks, see log below:

```
019-05-27 15:41:45.340 [INFO][1] migrate.go 64: checking host-local IPAM data dir dir existence...
2019-05-27 15:41:45.340 [INFO][1] migrate.go 71: retrieving node for IPIP tunnel address
2019-05-27 15:41:45.343 [INFO][1] migrate.go 134: checking if host-local IPAM data dir dir is empty...
2019-05-27 15:41:45.343 [INFO][1] migrate.go 157: host-local IPAM data dir is not empty, migrating...
2019-05-27 15:41:45.343 [INFO][1] migrate.go 165: setting datastore readiness to false
2019-05-27 15:41:45.357 [INFO][1] migrate.go 186: successfully set datastore readiness to false
2019-05-27 15:41:45.357 [INFO][1] migrate.go 189: removing cni binaries...
2019-05-27 15:41:45.357 [INFO][1] migrate.go 194: successfully removed cni binary! binary="/host/opt/cni/bin/calico"
2019-05-27 15:41:45.357 [INFO][1] migrate.go 194: successfully removed cni binary! binary="/host/opt/cni/bin/host-local"
2019-05-27 15:41:50.357 [INFO][1] migrate.go 201: acquiring lock on host-local IPAM
2019-05-27 15:41:50.357 [INFO][1] migrate.go 209: successfully acquired lock on host-local IPAM
2019-05-27 15:41:50.357 [INFO][1] migrate.go 222: mapping pod ips to pods...
2019-05-27 15:41:50.372 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.14" namespace="ams-testing-dev" pod="nc-pod-830748-5b7d8c44d7-zpzrv"
2019-05-27 15:41:50.372 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.23" namespace="ams-testing-dev" pod="nc-pod-834266-7ff6fd94bb-dcfsw"
2019-05-27 15:41:50.372 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.6" namespace="ams-testing-qa" pod="spring-boot-demo-service-any-qa-6d5bc4b9c6-8b9ld"
2019-05-27 15:41:50.372 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.54" namespace="ams-tooling-qa" pod="hclookingglass-any-qa-77c55c5989-n8zkf"
2019-05-27 15:41:50.372 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.10" namespace="gocdmaster-ams-helper" pod="fluentd-application-logging-6mdkp"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.15" namespace="gocdmaster-kubeconformance-helper" pod="fluentd-application-logging-762p5"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.11" namespace="ingress-controller" pod="traefik-ingress-controller-personal-75cfbbfb57-5r4t7"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.2" namespace="ingress-controller" pod="traefik-ingress-controller-system-864fcb77b4-tsh67"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.50" namespace="ingress-controller" pod="traefik-ingress-controller-team-ams-7555797867-dwzwm"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="istio-system" pod="istio-cni-node-rkxlt"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.27" namespace="istio-system" pod="istio-pilot-7c64c9d7d4-scblm"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="" namespace="istio-system" pod="istio-policy-b5bd7c5c7-zhmnp"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.8" namespace="jaeger-system" pod="jaeger-agent-zlgkc"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="kube-system" pod="calico-node-zpwgh"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="kube-system" pod="haproxy-kworker-be-sandbox-iz2-bap004"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="" namespace="kube-system" pod="heapster-7b67d644c-4dcsz"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.7" namespace="kube-system" pod="kube-dns-bc9cf5fbd-dhh4m"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="kube-system" pod="kube-proxy-8gnzv"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.43" namespace="kube-system" pod="local-volume-provisioner-plc5f"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="kube-system" pod="supportive-etcd-1"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.4" namespace="logging" pod="fluentd-cluster-logging-7lf5m"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.12" namespace="logging" pod="fluentd-exporter-vl7v8"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="metallb-system" pod="speaker-68fc77fbc8-8m57k"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="" namespace="monitoring" pod="data-plane-availability-nginx-56bd4d7c5-72xbb"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="monitoring" pod="dellhw-exporter-4b2fw"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.5" namespace="monitoring" pod="kuberhealthy-7965d596d8-h9mns"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="10.242.195.5" namespace="monitoring" pod="node-exporter-4j96r"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.22" namespace="monitoring" pod="persistent-volume-exporter-77566b4d96-qxn7n"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.20" namespace="monitoring" pod="prometheus-0"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.19" namespace="monitoring" pod="slo-monitor-64874d6574-g7ctz"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 232: mapping in pod IP="100.64.3.21" namespace="monitoring" pod="ssl-file-exporter-node-fzczn"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 235: successfully mapped pod ips to pods!
2019-05-27 15:41:50.373 [INFO][1] migrate.go 238: reading files from host-local IPAM data dir...
2019-05-27 15:41:50.373 [INFO][1] migrate.go 247: processing file... file="100.64.3.11"
2019-05-27 15:41:50.373 [INFO][1] migrate.go 291: assinging pod IP to Calico IPAM... file="100.64.3.11"
2019-05-27 15:41:50.373 [INFO][1] ipam.go 581: Assigning IP 100.64.3.11 to host: kworker-be-sandbox-iz2-bap004
2019-05-27 15:41:50.378 [ERROR][1] ipam.go 635: Failed to assign address 100.64.3.11: Address already assigned in block
2019-05-27 15:41:50.378 [INFO][1] migrate.go 212: releasing lock on host-local backend...
2019-05-27 15:41:50.378 [INFO][1] migrate.go 216: successfully released lock on host-local backend!
2019-05-27 15:41:50.378 [ERROR][1] ipam_plugin.go 95: failed to migrate ipam, retrying... error=failed to assign IP to calico backend: Address already assigned in block node="kworker-be-sandbox-iz2-bap004"
```

The relevant IPAMBlock for this error looks like this:

```yaml
- apiVersion: crd.projectcalico.org/v1
  kind: IPAMBlock
  metadata:
    annotations:
      projectcalico.org/metadata: '{"creationTimestamp":null}'
    creationTimestamp: "2019-05-19T04:32:22Z"
    generation: 7
    name: 100-64-3-0-26
    resourceVersion: "2966556"
    selfLink: /apis/crd.projectcalico.org/v1/ipamblocks/100-64-3-0-26
    uid: 188c0983-79ef-11e9-9af8-246e96bd5e84
  spec:
    Deleted: false
    affinity: host:kworker-be-sandbox-iz2-bap004
    allocations:
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - 5
    - 4
    - null
    - null
    - null
    - null
    - 0
    - null
    - null
    - null
    - null
    - null
    - 2
    - null
    - 1
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - 3
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    attributes:
    - handle_id: k8s-pod-network.8bc16dfe3c87b1f0fb3b3dbd20e51f64129b5bbc8e3794c063ac14d9ca500dd5
      secondary:
        namespace: ingress-controller
        node: kworker-be-sandbox-iz2-bap004
        pod: traefik-ingress-controller-system-864fcb77b4-985mv
    - handle_id: k8s-pod-network.620acea7fd8fb70f1be8fbcfc901a006d3dad4ce57f0f81fb700a988a899e0eb
      secondary:
        namespace: istio-system
        node: kworker-be-sandbox-iz2-bap004
        pod: istio-sidecar-injector-dd5d4f4cc-4g9tt
    - handle_id: k8s-pod-network.5de3d699f94390b15a0d7fb6d291363d10ba7e80f994b3ff7d21699ee3628c5a
      secondary:
        namespace: monitoring
        node: kworker-be-sandbox-iz2-bap004
        pod: kuberhealthy-7965d596d8-h9mns
    - handle_id: k8s-pod-network.41a3e38b2682670a528e4f0519ec2e1df89dbcbf4b7b4ad03c15f8c30403b9a8
      secondary:
        namespace: monitoring
        node: kworker-be-sandbox-iz2-bap004
        pod: prometheus-0
    - handle_id: k8s-pod-network.437f76f9ec35f183895367dbfa531573e00330843e02a14ead14ad255e7b37c2
      secondary:
        namespace: jaeger-system
        node: kworker-be-sandbox-iz2-bap004
        pod: jaeger-query-74bfc79bdb-xb9rl
    - handle_id: k8s-pod-network.9ba3cbaabf9b199ee8e0194000f11eac4daa8328de2fc59a57c3b11b2f3f73c3
      secondary:
        namespace: gocdmaster-ams-helper
        node: kworker-be-sandbox-iz2-bap004
        pod: fluentd-application-logging-6mdkp
    cidr: 100.64.3.0/26
    strictAffinity: false
    unallocated:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 12
    - 13
    - 14
    - 15
    - 17
    - 18
    - 19
    - 20
    - 21
    - 23
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 61
    - 62
    - 63
```

## Possible Solution

A workaround for us is deleting the `100-64-3-0-26` IPAMBlock, after that the migration works.
A possible solution would be checking the IPAMBlocks when migrating and resolving conflicts (e.g. by skipping existing IP addresses).
I have found a bug in locking for which I will submit a pull request after this issue. This could cause a race condition in which local IPAM writes addresses during migration causing the upgrade-ipam to think that migration did not yet finish on subsequent restarts of calico-node.

## Steps to Reproduce (for bugs)

It seems like this is a race condition, so reproduction isn't easy. It happened for two test-deployments for us after multiple days of operation. To my current knowledge the steps for reproducing are somewhat like
1. Start with a kubernetes cluster with Calico v3.5.4.
2. Upgrade to Calico v3.7.2 following [the getting started steps](https://docs.projectcalico.org/v3.7/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastore50-nodes-or-less)
3. Observe that calico initally starts and works
4. Simulatenously kill calico-node pods and start deployments
5. (Hopefully) observe at some point, that Calico is stuck in `Init:0/1`
6. On the node, that has the stuck Calico pod you should observe that two directories exist: `/var/lib/cni/networks/k8s-pod-network` (the host-local IPAM directory) and `/var/lib/cni/networks/var/lib/cni/networks/k8s-pod-network`, the directory erronously created in migrate.go when attempting to log the host-local IPAM directory

## Context

We are trying to upgrade Calico v.3.5.4 to v3.7.2 and use the new Calico-IPAM afterwards.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): Calico `v3.7.2`
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes `v1.14.1`
* CNI config:
```yaml
cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "log_level": "warning",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": 1500,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
            "type": "k8s",
            "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
            "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "externalSetMarkChain": "KUBE-MARK-MASQ",
          "capabilities": {"portMappings": true}
        }
      ]
    }
```
* Operating System and version: `Container Linux by CoreOS 2079.4.0 (Rhyolite)   4.19.43-coreos `
* Link to your project (optional):

**Comment by maxbischoff** [comment]
I have succesfully reproduced the bug with following (slightly adjusted) steps:
1. Start with a kubernetes cluster with Calico v3.5.4.
2. Upgrade to Calico v3.7.2 following the getting started steps
3. Schedule pods repeatedly using `kubectl run nginx --image=nginx --replicas=20`
4. Observe that at least one new Calico pod is stuck in Init:0/1
5. On the node, that has the stuck Calico pod you should observe that two directories exist: /var/lib/cni/networks/k8s-pod-network (the host-local IPAM directory) and /var/lib/cni/networks/var/lib/cni/networks/k8s-pod-network, the directory erronously created in migrate.go when attempting to log the host-local IPAM directory

**Comment by johscheuer** [comment]
I used the Patch provided by @maxbischoff and tested the upgrade 10x and I didn't see any stuck upgrade pods, so I assume that the bug is fixed by https://github.com/projectcalico/cni-plugin/pull/750 or I'm just extremely lucky :)

The main error was that the hostLocal IPAM wasn't locked because the faulty code reserved a lock for hostLocal IPAM in the wrong directory which means the actual hostLocal IPAM was never locked (which introduced this race condition).

**Comment by neiljerram** [comment]
@maxbischoff @johscheuer I've merged #750, and I very much appreciate your work on reporting and debugging this, and retesting with the #750 fix in place.

There's no doubt that #750 is a good fix, but I am struggling to describe a precise sequence of events that takes advantage of the #750 bug and results in the observations as described above; and hence I can't yet feel confident that #750 was the _only_ problem here.

In case either of you have more logs lying around from when you were seeing the problem here, I'd love to see those.  In particular, when a log like the one above was taken from the "upgrade-ipam" initContainer, I'd expect it possibly to show previous upgrade attempt cycles - as the behavior of this initContainer is that it keeps retrying, at intervals of 1s, until the migration succeeds.

One specific query, @maxbischoff - does the IPAMBlock YAML above come from the same upgrade experiment as the preceding logs?  My reason for asking is that the logs are dated 2019-05-27 15:41, but the IPAMBlock says it was created on 2019-05-19, i.e. 8 days earlier.

If you do have further thoughts on any of the above, please do let me know.

**Comment by maxbischoff** [comment]
[Here](https://github.com/projectcalico/cni-plugin/files/3250752/upgrade-ipam.log) is the complete log, it indeed has many retries until I fixed the upgrade by deleting the IPAMBlock from my above excerpt.
This IPAMBlock comes from the time of the upgrade-ipam log. The upgrade was AFAIK falsely triggered after a restart of one of our calico-node pods approximately a week after the actual upgrade from Calico 3.5.4 to Calico 3.7.2. This would mean, that the upgrade was finished without a conflict in IPAMBlocks the first time, but the host-local IPAM directory not deleted (as the directory is used as indicator for the migration).

**Comment by neiljerram** [comment]
Thanks @maxbischoff , that helps to explain the whole scenario.

The remaining question now is: after the original upgrade completed - which I believe means that it wiped the host-local IPAM directory, and the following initContainer installed the calico-ipam binary and CNI config - how did another instance of host-local IPAM run and write a new file into the directory?  I'm afraid I still don't understand that in detail.

Independently, though, I noticed that the migrate.go code is intending to be resilient to this scenario anyway, and only fails to be so because of a bug in how it detects the "already assigned"; I've put up https://github.com/projectcalico/cni-plugin/pull/754 to improve that.

**Comment by neiljerram** [comment]
I think there's a good chance that #750 and #754 have sufficiently addressed this issue, so I'll close it now.  Thanks @maxbischoff @johscheuer for your reports, testing and help.  In case you do still see this problem, please feel free to reopen or to raise a new issue.
